export const SET_VAR = 'SET_VAR'
export const SET_PATH       = 'SET_PATH'
export const SET_USER       = 'SET_USER'
export const SET_USER_IP    = 'SET_USER_IP'
export const SET_SNACK      = 'SET_SNACK'
export const SET_NEW_EVENT  = 'SET_NEW_EVENT'
export const SET_SORT_FIELD = 'SET_SORT_FIELD'
export const SET_NEW_QUESTION = 'SET_NEW_QUESTION'

export const FETCH_EVENTS   = 'FETCH_EVENTS'
export const OBSERVE_EVENTS = 'OBSERVE_EVENTS'
export const GET_EVENT      = 'GET_EVENT'
export const ADD_EVENT   = 'ADD_EVENT'
export const UPDATE_EVENT   = 'UPDATE_EVENT'
export const DELETE_EVENT   = 'DELETE_EVENT'
export const SET_EVENT      = 'SET_EVENT'
export const OBSERVE_EVENT  = 'OBSERVE_EVENT'

export const FETCH_QUESTIONS    = 'FETCH_QUESTIONS'
export const OBSERVE_QUESTIONS  = 'OBSERVE_QUESTIONS'
export const GET_QUESTION       = 'GET_QUESTION'
export const ADD_QUESTION    = 'ADD_QUESTION'
export const UPDATE_QUESTION    = 'UPDATE_QUESTION'
export const DELETE_QUESTION    = 'DELETE_QUESTION'
export const HIGHLIGHT_QUESTION = 'HIGHLIGHT_QUESTION'
export const LIKE_QUESTION      = 'LIKE_QUESTION'
export const SET_QUESTION       = 'SET_QUESTION'
export const OBSERVE_QUESTION   = 'OBSERVE_QUESTION'
