export const SET_USER       = 'SET_USER'
export const SET_SNACK      = 'SET_SNACK'
export const SET_NEW_EVENT  = 'SET_NEW_EVENT'

export const FETCH_EVENTS   = 'FETCH_EVENTS'
export const OBSERVE_EVENTS = 'OBSERVE_EVENTS'
export const GET_EVENT      = 'GET_EVENT'
export const CREATE_EVENT   = 'CREATE_EVENT'
export const UPDATE_EVENT   = 'UPDATE_EVENT'
export const DELETE_EVENT   = 'DELETE_EVENT'

export const FETCH_QUESTIONS    = 'FETCH_QUESTIONS'
export const OBSERVE_QUESTIONS  = 'OBSERVE_QUESTIONS'
export const GET_QUESTION       = 'GET_QUESTION'
export const CREATE_QUESTION    = 'CREATE_QUESTION'
export const UPDATE_QUESTION    = 'UPDATE_QUESTION'
export const DELETE_QUESTION    = 'DELETE_QUESTION'
export const HIGHLIGHT_QUESTION = 'HIGHLIGHT_QUESTION'
export const LIKE_QUESTION      = 'LIKE_QUESTION'
