export const SET_USER = 'SET_USER'

export const FETCH_EVENTS = 'FETCH_EVENTS'
export const CREATE_EVENT = 'CREATE_EVENT'
export const UPDATE_EVENT = 'UPDATE_EVENT'
export const DELETE_EVENT = 'DELETE_EVENT'

export const FETCH_QUESTIONS = 'FETCH_QUESTIONS'
export const CREATE_QUESTION = 'CREATE_QUESTION'
export const UPDATE_QUESTION = 'UPDATE_QUESTION'
export const DELETE_QUESTION = 'DELETE_QUESTION'
